### ISSUE TITLE
breaking changes for 4.x

### ISSUE THREAD

**Issue by jacobbednarz** [cloudflare/terraform-provider-cloudflare#1646]
Tracking for all the planned cleanup in 4.x

## Internal cleanup 

- [x] Remove all uses of `UsingAccount` in favour of explicit account ID parameters. (#2139)
- [x] Remove reliance on `userBaseUrl`.
- [x] Remove all references to `client.AccountID`. (#2154)

## Schema updates

- [x] `cloudflare_byo_ip_prefix` `prefix_id` should be internal `id`, not a custom attribute.

### Deletions/modifications

- [x] `cloudflare_spectrum_application` needs to support a list of config options (not just IP list) in `edge_ips` (#2219)
- [x] `cloudflare_zone` to swap `account_id` to `Required: true` (from optional) (#2153)
- [x] `cloudflare_load_balancer_pool` to swap `account_id` to `Required: true` (from optional) (#2153)
- [x] `cloudflare_load_balancer_monitor` to swap `account_id` to `Required: true` (from optional) (#2153)
- [x] `cloudflare_account_member` to swap `account_id` to `Required: true` (from optional) (#2153)
- [x] `cloudflare_workers_kv_namespace` to swap `account_id` to `Required: true` (from optional) (#2153)
- [x] `cloudflare_workers_kv` to swap `account_id` to `Required: true` (from optional) (#2153)
- [x] `cloudflare_workers_script` to swap `account_id` to `Required: true` (from optional) (#2153)
- [x] remove ability to create user level resources
  - [x] `cloudflare_access_rule` (#2157)
  - [x] `cloudflare_load_balancer` (#2157)
  - [x] `cloudflare_load_balancer_monitor` (#2157)
  - [x] `cloudflare_load_balancer_pool` (#2157)

### Additions

- [x] `cloudflare_zone` needs to support `account_id` (#1767)
- [x] `cloudflare_account_member` needs to support `account_id` (#1767)
- [x] `cloudflare_access_rule` needs to support `account_id` (#1790)
- [x] `cloudflare_load_balancer_pool` needs to support `account_id` (#1986)
- [x] `cloudflare_load_balancer_monitor` needs to support `account_id` (#1986)
- [x] `cloudflare_workers_kv` needs to support `account_id` (#2049)
- [x] `cloudflare_workers_kv_namespace` needs to support `account_id` (#2049)
- [x] `cloudflare_worker_script` needs to support `account_id` (#2102)
- [x] ~`cloudflare_worker_route` needs to support `account_id`~ only supported at the zone level for now
- [x] `cloudflare_worker_cron_trigger` needs to support `account_id`

## Deprecations

- [x] `cloudflare_argo_tunnel` => `cloudflare_tunnel` (#2135)
- [x] Remove `cloudflare_access_bookmark` resource in favour of configuration on `cloudflare_access_application` (#2136).
- [x] Legacy WAF configuration 
  - [x] `cloudflare_waf_group` (resource) (#2138)
  - [x] `cloudflare_waf_override` (resource) (#2138)
  - [x] `cloudflare_waf_package` (resource) (#2138)
  - [x] `cloudflare_waf_rule` (resource) (#2138)
  - [x] `cloudflare_waf_groups` (datasource) (#2138)
  - [x] `cloudflare_waf_packages` (datasource) (#2138)
  - [x] `cloudflare_waf_rules` (datasource) (#2138)
- [x] `cloudflare_ip_list` (replaced by `cloudflare_list`) (#2137)

**Comment by Nmishin** [comment]
Seems `account_id ` should be added to the `cloudflare_worker_script` as well.
If I try to run terraform apply without `export CLOUDFLARE_ACCOUNT_ID` it fails with error:
```│ Error: error creating worker script: account ID required
│ 
│   with module.workers.cloudflare_worker_script.main["cors"],
│   on .terraform/modules/workers/cloudflare/worker/main.tf line 17, in resource "cloudflare_worker_script" "main":
│   17: resource "cloudflare_worker_script" "main" {
│

**Comment by jacobbednarz** [comment]
thanks @Nmishin - added.

**Comment by jacobbednarz** [comment]
thanks, added.

**Comment by andy-paine-numan** [comment]
Another addition that needs `account_id` support - [cloudflare_worker_route](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/resources/worker_route.md#cloudflare_worker_route)

**Comment by jacobbednarz** [comment]
> Another addition that needs `account_id` support - [cloudflare_worker_route](https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/docs/resources/worker_route.md#cloudflare_worker_route)

thanks, updated

**Comment by andrewkrain** [comment]
It seems that `account_id` was added to most account-level resources in 3.27.0. However, this doesn't seem to enforce the use of account-level API (unlike specifying `account_id` on provider level or using the CLOUDFLARE_ACCOUNT_ID environment variable, which is now deprecated).

**Comment by jacobbednarz** [comment]
@andrewkrain please open a new issue following the template provided for the resources you're having issues with so we can address those specifically and just link back to this larger tracking ticket.

**Comment by Cyb3r-Jak3** [comment]
Seems like `ip_list` should be deprecated in favor of `list`
https://github.com/cloudflare/terraform-provider-cloudflare/blob/master/internal/provider/resource_cloudflare_ip_list.go#L15-L16

**Comment by jacobbednarz** [comment]
thanks @Cyb3r-Jak3; added.
